name: googleflutter
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.0
  google_sign_in: ^6.2.2
  firebase_messaging: ^15.2.4
  cloud_firestore: ^5.6.5
  font_awesome_flutter: ^10.8.0
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^18.0.1
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/comlogo.png
    - assets/images/google.png
    - assets/images/perfil.png




flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/google.png"
  min_sdk_android: 21
  remove_alpha_ios: true
